version: 1.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\Properties\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: '*nupkg'
  on:
    branch: /release-\d+\.\d+\.\d+/
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: baGcokT/eXrx8B//7faaAAaXz8p44qklJXHH2ioXNUzIHz949ZyGxRWUn1Ae+BJq
  artifact: '*nupkg'
  on:
    branch: /release-\d+\.\d+\.\d+/
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
